// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';

export function ApplyUpdate(arg1:string):Promise<string>;

export function CheckUpdate():Promise<updater.UpdateInfo>;

export function DownloadUpdate(arg1:string):Promise<string>;
