// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['updater']['API']['ApplyUpdate'](arg1);
}

export function CheckUpdate() {
  return window['go']['updater']['API']['CheckUpdate']();
}

export function DownloadUpdate(arg1) {
  return window['go']['updater']['API']['DownloadUpdate'](arg1);
}

export function GetUpdateURL() {
  return window['go']['updater']['API']['GetUpdateURL']();
}

export function SetUpdateURL(arg1) {
  return window['go']['updater']['API']['SetUpdateURL'](arg1);
}

export function Startup(arg1) {
  return window['go']['updater']['API']['Startup'](arg1);
}
