// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktoplock} from '../models';
import {context} from '../models';

export function Backup():Promise<desktoplock.BackupResult>;

export function ChangeDefaultPassword(arg1:string):Promise<boolean|string>;

export function ChangePassword(arg1:string,arg2:string):Promise<boolean|string>;

export function DeleteBackup(arg1:string):Promise<boolean>;

export function GetBackupIcons():Promise<Record<string, string>>;

export function IsDefaultPassword():Promise<boolean>;

export function ListBackups():Promise<Array<desktoplock.BackupItem>>;

export function Lock():Promise<boolean>;

export function Restore():Promise<desktoplock.RestoreResult>;

export function Startup(arg1:context.Context):Promise<void>;

export function Status():Promise<desktoplock.StatusResult>;

export function Unlock():Promise<boolean>;

export function VerifyPassword(arg1:string):Promise<boolean>;
