// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backup() {
  return window['go']['desktoplock']['API']['Backup']();
}

export function ChangeDefaultPassword(arg1) {
  return window['go']['desktoplock']['API']['ChangeDefaultPassword'](arg1);
}

export function ChangePassword(arg1, arg2) {
  return window['go']['desktoplock']['API']['ChangePassword'](arg1, arg2);
}

export function DeleteBackup(arg1) {
  return window['go']['desktoplock']['API']['DeleteBackup'](arg1);
}

export function GetBackupIcons() {
  return window['go']['desktoplock']['API']['GetBackupIcons']();
}

export function IsDefaultPassword() {
  return window['go']['desktoplock']['API']['IsDefaultPassword']();
}

export function ListBackups() {
  return window['go']['desktoplock']['API']['ListBackups']();
}

export function Lock() {
  return window['go']['desktoplock']['API']['Lock']();
}

export function Restore() {
  return window['go']['desktoplock']['API']['Restore']();
}

export function Startup(arg1) {
  return window['go']['desktoplock']['API']['Startup'](arg1);
}

export function Status() {
  return window['go']['desktoplock']['API']['Status']();
}

export function Unlock() {
  return window['go']['desktoplock']['API']['Unlock']();
}

export function VerifyPassword(arg1) {
  return window['go']['desktoplock']['API']['VerifyPassword'](arg1);
}
