// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pyenv} from '../models';
import {context} from '../models';

export function AvailablePackages():Promise<Array<pyenv.PackageInfo>>;

export function CheckStatus():Promise<pyenv.InstallStatus>;

export function InstallPackages(arg1:Array<string>):Promise<pyenv.ProgressInfo>;

export function InstallPython():Promise<pyenv.ProgressInfo>;

export function InstallWithElevation(arg1:Array<string>):Promise<pyenv.ProgressInfo>;

export function Startup(arg1:context.Context):Promise<void>;
