// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AvailablePackages() {
  return window['go']['pyenv']['InstallerAPI']['AvailablePackages']();
}

export function CheckStatus() {
  return window['go']['pyenv']['InstallerAPI']['CheckStatus']();
}

export function InstallWithElevation(arg1) {
  return window['go']['pyenv']['InstallerAPI']['InstallWithElevation'](arg1);
}

export function InstallWithPackages(arg1) {
  return window['go']['pyenv']['InstallerAPI']['InstallWithPackages'](arg1);
}

export function Startup(arg1) {
  return window['go']['pyenv']['InstallerAPI']['Startup'](arg1);
}
