// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmQuit():Promise<void>;

export function GetVersion():Promise<string>;

export function IsAutoStart():Promise<boolean>;

export function SetAutoStart(arg1:boolean):Promise<boolean>;
