// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmQuit() {
  return window['go']['main']['App']['ConfirmQuit']();
}

export function IsAutoStart() {
  return window['go']['main']['App']['IsAutoStart']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}
